
package gui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.formdev.flatlaf.ui.FlatTextBorder;
import com.toedter.calendar.JDateChooser;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import logic.FieldValidator;
import logic.ImageHandler;
import logic.RecordAdder;

public class AddPatientForm extends javax.swing.JFrame {

    String imagePath = null;
    /**
     * Creates new form AddPatientForm
     */
    public AddPatientForm() {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AddPatientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        jRadioButtonMale.setActionCommand("Male");
        jRadioButtonFemale.setActionCommand("Female");
        jRadioButtonOther.setActionCommand("Other");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSex = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldEmgLname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldEmgFname = new javax.swing.JTextField();
        jLabelBlood = new javax.swing.JLabel();
        jComboBoxBlood = new javax.swing.JComboBox<>();
        jLabelDob = new javax.swing.JLabel();
        jDateChooserDob = new com.toedter.calendar.JDateChooser();
        jLabelPhone = new javax.swing.JLabel();
        jComboBoxEmgCountryCode = new javax.swing.JComboBox<>();
        jTextFieldEmgPhoneX = new javax.swing.JTextField();
        jTextFieldEmgPhoneY = new javax.swing.JTextField();
        jTextFieldEmgPhoneZ = new javax.swing.JTextField();
        jLabelStreet = new javax.swing.JLabel();
        jTextFieldStreet = new javax.swing.JTextField();
        jLabelBarangay = new javax.swing.JLabel();
        jTextFieldBarangay = new javax.swing.JTextField();
        jLabelCity = new javax.swing.JLabel();
        jTextFieldCity = new javax.swing.JTextField();
        jLabelProvince = new javax.swing.JLabel();
        jTextFieldProvince = new javax.swing.JTextField();
        jLabelCountry = new javax.swing.JLabel();
        jTextFieldCountry = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabelPicName = new javax.swing.JLabel();
        jLabelPic = new javax.swing.JLabel();
        jButtonBrowse = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();
        jLabelSex = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonOther = new javax.swing.JRadioButton();
        jLabelPhone1 = new javax.swing.JLabel();
        jComboBoxCountryCode = new javax.swing.JComboBox<>();
        jTextFieldPhoneX = new javax.swing.JTextField();
        jTextFieldPhoneY = new javax.swing.JTextField();
        jTextFieldPhoneZ = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Add a Patient");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 30, 90, 16);

        jLabel2.setText("First name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 70, 70, 16);

        jTextFieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFname);
        jTextFieldFname.setBounds(250, 90, 130, 22);

        jLabel3.setText("Middle name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 70, 80, 16);

        jTextFieldMname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldMname);
        jTextFieldMname.setBounds(410, 90, 130, 22);

        jLabel4.setText("Last name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(570, 70, 70, 16);

        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldLname);
        jTextFieldLname.setBounds(570, 90, 130, 22);

        jLabel5.setText("Email:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 190, 70, 16);

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(520, 210, 130, 22);

        jLabel9.setText("Last name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(230, 390, 70, 16);

        jTextFieldEmgLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmgLnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmgLname);
        jTextFieldEmgLname.setBounds(230, 410, 130, 22);

        jLabel11.setText("First name");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 390, 70, 16);

        jTextFieldEmgFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmgFnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmgFname);
        jTextFieldEmgFname.setBounds(60, 410, 130, 22);

        jLabelBlood.setText("Blood Type");
        jPanel1.add(jLabelBlood);
        jLabelBlood.setBounds(240, 130, 60, 16);

        jComboBoxBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O-", "O+", "B-", "B+", "A-", "A+", "AB-", "AB+" }));
        jComboBoxBlood.setSelectedIndex(-1);
        jPanel1.add(jComboBoxBlood);
        jComboBoxBlood.setBounds(230, 150, 80, 22);

        jLabelDob.setText("Date of Birth:");
        jPanel1.add(jLabelDob);
        jLabelDob.setBounds(350, 130, 69, 16);

        jDateChooserDob.setDateFormatString("MMMMMMMMM d, y");
        jPanel1.add(jDateChooserDob);
        jDateChooserDob.setBounds(340, 150, 130, 22);

        jLabelPhone.setText("Phone Number:");
        jPanel1.add(jLabelPhone);
        jLabelPhone.setBounds(400, 390, 84, 16);

        jComboBoxEmgCountryCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+63" }));
        jPanel1.add(jComboBoxEmgCountryCode);
        jComboBoxEmgCountryCode.setBounds(390, 410, 60, 22);

        jTextFieldEmgPhoneX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmgPhoneX.setText("XXX");
        jTextFieldEmgPhoneX.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneX.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneX.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneXFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldEmgPhoneX);
        jTextFieldEmgPhoneX.setBounds(460, 410, 40, 20);

        jTextFieldEmgPhoneY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmgPhoneY.setText("YYY");
        jTextFieldEmgPhoneY.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneY.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneY.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneYFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneYFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldEmgPhoneY);
        jTextFieldEmgPhoneY.setBounds(510, 410, 40, 20);

        jTextFieldEmgPhoneZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmgPhoneZ.setText("ZZZZ");
        jTextFieldEmgPhoneZ.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneZ.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneZ.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneZ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneZFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneZFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldEmgPhoneZ);
        jTextFieldEmgPhoneZ.setBounds(560, 410, 50, 20);

        jLabelStreet.setText("Street");
        jPanel1.add(jLabelStreet);
        jLabelStreet.setBounds(60, 240, 30, 16);

        jTextFieldStreet.setText("Blk # Lot # Phase #");
        jTextFieldStreet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldStreetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldStreetFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldStreet);
        jTextFieldStreet.setBounds(50, 260, 140, 22);

        jLabelBarangay.setText("Barangay");
        jPanel1.add(jLabelBarangay);
        jLabelBarangay.setBounds(200, 240, 70, 16);

        jTextFieldBarangay.setText("Barangay #");
        jTextFieldBarangay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBarangayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBarangayFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldBarangay);
        jTextFieldBarangay.setBounds(190, 260, 120, 22);

        jLabelCity.setText("City");
        jPanel1.add(jLabelCity);
        jLabelCity.setBounds(320, 240, 21, 16);

        jTextFieldCity.setText("Dasmariñas City");
        jTextFieldCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCityFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldCity);
        jTextFieldCity.setBounds(310, 260, 110, 22);

        jLabelProvince.setText("Provice");
        jPanel1.add(jLabelProvince);
        jLabelProvince.setBounds(430, 240, 39, 16);

        jTextFieldProvince.setText("Cavite");
        jTextFieldProvince.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProvinceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProvinceFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldProvince);
        jTextFieldProvince.setBounds(420, 260, 100, 22);

        jLabelCountry.setText("Country:");
        jPanel1.add(jLabelCountry);
        jLabelCountry.setBounds(530, 240, 46, 16);

        jTextFieldCountry.setText("Philippines");
        jTextFieldCountry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCountryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCountryFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldCountry);
        jTextFieldCountry.setBounds(520, 260, 125, 22);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 310, 740, 20);

        jLabel12.setText("Emergency Contact");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 340, 120, 16);

        jLabelPicName.setText("Picture");
        jPanel1.add(jLabelPicName);
        jLabelPicName.setBounds(100, 60, 37, 16);

        jLabelPic.setBackground(new java.awt.Color(153, 255, 255));
        jLabelPic.setOpaque(true);
        jPanel1.add(jLabelPic);
        jLabelPic.setBounds(60, 80, 120, 120);

        jButtonBrowse.setText("Browse");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBrowse);
        jButtonBrowse.setBounds(80, 210, 72, 23);

        jButtonReset.setText("Reset");
        jPanel1.add(jButtonReset);
        jButtonReset.setBounds(300, 480, 75, 23);

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubmit);
        jButtonSubmit.setBounds(380, 480, 72, 23);

        jLabelSex.setText("Sex:");
        jPanel1.add(jLabelSex);
        jLabelSex.setBounds(510, 130, 20, 16);

        buttonGroupSex.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonMale);
        jRadioButtonMale.setBounds(500, 150, 50, 21);

        buttonGroupSex.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");
        jPanel1.add(jRadioButtonFemale);
        jRadioButtonFemale.setBounds(560, 150, 70, 21);

        buttonGroupSex.add(jRadioButtonOther);
        jRadioButtonOther.setText("Other");
        jPanel1.add(jRadioButtonOther);
        jRadioButtonOther.setBounds(630, 150, 60, 21);

        jLabelPhone1.setText("Phone Number:");
        jPanel1.add(jLabelPhone1);
        jLabelPhone1.setBounds(270, 190, 84, 16);

        jComboBoxCountryCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+63" }));
        jPanel1.add(jComboBoxCountryCode);
        jComboBoxCountryCode.setBounds(260, 210, 60, 22);

        jTextFieldPhoneX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneX.setText("XXX");
        jTextFieldPhoneX.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneX.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneX.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneXFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldPhoneX);
        jTextFieldPhoneX.setBounds(330, 210, 40, 20);

        jTextFieldPhoneY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneY.setText("YYY");
        jTextFieldPhoneY.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneY.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneY.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneYFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneYFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldPhoneY);
        jTextFieldPhoneY.setBounds(380, 210, 40, 20);

        jTextFieldPhoneZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneZ.setText("ZZZZ");
        jTextFieldPhoneZ.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneZ.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneZ.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneZ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneZFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneZFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldPhoneZ);
        jTextFieldPhoneZ.setBounds(430, 210, 50, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFnameActionPerformed

    private void jTextFieldMnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMnameActionPerformed

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldEmgLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmgLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmgLnameActionPerformed

    private void jTextFieldEmgFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmgFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmgFnameActionPerformed

    private void jTextFieldEmgPhoneXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneXFocusGained
        if (jTextFieldEmgPhoneX.getText().equals("XXX")) {
            jTextFieldEmgPhoneX.setText("");
        }
        jTextFieldEmgPhoneX.setBorder(new FlatTextBorder());
    }//GEN-LAST:event_jTextFieldEmgPhoneXFocusGained

    private void jTextFieldEmgPhoneXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneXFocusLost
        if (jTextFieldEmgPhoneX.getText().isEmpty()) {
            jTextFieldEmgPhoneX.setText("XXX");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneXFocusLost

    private void jTextFieldEmgPhoneYFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneYFocusGained
        if (jTextFieldEmgPhoneY.getText().equals("YYY")) {
            jTextFieldEmgPhoneY.setText("");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneYFocusGained

    private void jTextFieldEmgPhoneYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneYFocusLost
        if (jTextFieldEmgPhoneY.getText().isEmpty()) {
            jTextFieldEmgPhoneY.setText("YYY");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneYFocusLost

    private void jTextFieldEmgPhoneZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneZFocusGained
        if (jTextFieldEmgPhoneZ.getText().equals("ZZZZ")) {
            jTextFieldEmgPhoneZ.setText("");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneZFocusGained

    private void jTextFieldEmgPhoneZFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneZFocusLost
        if (jTextFieldEmgPhoneZ.getText().isEmpty()) {
            jTextFieldEmgPhoneZ.setText("ZZZZ");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneZFocusLost

    private void jTextFieldStreetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStreetFocusGained
        if (jTextFieldStreet.getText().equals("Blk # Lot # Phase #")) {
            jTextFieldStreet.setText("");
        }
    }//GEN-LAST:event_jTextFieldStreetFocusGained

    private void jTextFieldStreetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStreetFocusLost
        if (jTextFieldStreet.getText().isEmpty()) {
            jTextFieldStreet.setText("Blk # Lot # Phase #");
        }
    }//GEN-LAST:event_jTextFieldStreetFocusLost

    private void jTextFieldBarangayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBarangayFocusGained
        if (jTextFieldBarangay.getText().equals("Barangay #")) {
            jTextFieldBarangay.setText("");
        }
    }//GEN-LAST:event_jTextFieldBarangayFocusGained

    private void jTextFieldBarangayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBarangayFocusLost
        if (jTextFieldBarangay.getText().isEmpty()) {
            jTextFieldBarangay.setText("Barangay #");
        }
    }//GEN-LAST:event_jTextFieldBarangayFocusLost

    private void jTextFieldCityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCityFocusGained
        if (jTextFieldCity.getText().equals("Dasmariñas City")) {
            jTextFieldCity.setText("");
        }
    }//GEN-LAST:event_jTextFieldCityFocusGained

    private void jTextFieldCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCityFocusLost
        if (jTextFieldCity.getText().isEmpty()) {
            jTextFieldCity.setText("Dasmariñas City");
        }
    }//GEN-LAST:event_jTextFieldCityFocusLost

    private void jTextFieldProvinceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProvinceFocusGained
        if (jTextFieldProvince.getText().equals("Cavite")) {
            jTextFieldProvince.setText("");
        }
    }//GEN-LAST:event_jTextFieldProvinceFocusGained

    private void jTextFieldProvinceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProvinceFocusLost
        if (jTextFieldProvince.getText().isEmpty()) {
            jTextFieldProvince.setText("Cavite");
        }
    }//GEN-LAST:event_jTextFieldProvinceFocusLost

    private void jTextFieldCountryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCountryFocusGained
        if (jTextFieldCountry.getText().equals("Philippines")) {
            jTextFieldCountry.setText("");
        }
    }//GEN-LAST:event_jTextFieldCountryFocusGained

    private void jTextFieldCountryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCountryFocusLost
        if (jTextFieldCountry.getText().isEmpty()) {
            jTextFieldCountry.setText("Philippines");
        }
    }//GEN-LAST:event_jTextFieldCountryFocusLost

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        ImageHandler imageHandler = new ImageHandler();
        imagePath = imageHandler.browseImage(this);

        if (imagePath != null) {
            jLabelPic.setIcon(imageHandler.resizeImage(jLabelPic, imagePath));
        }
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        //        String username = jTextFieldUsername.getText();
        //        String password = jTextFieldPassword.getText();
        //        String fname = jTextFieldFname.getText();
        //        String mname = jTextFieldMname.getText();
        //        String lname = jTextFieldLname.getText();
        //        String position = (String) jComboBoxPosition.getSelectedItem();
        //        String title  = (String) jComboBoxJob.getSelectedItem();
        //        Date dob = jDateChooserDob.getDate();
        //        String blood = (String) jComboBoxBlood.getSelectedItem();

        JTextField[] textArray = {jTextFieldFname, jTextFieldMname, jTextFieldLname, jTextFieldPhoneX, jTextFieldPhoneY, jTextFieldPhoneZ, jTextFieldEmail, jTextFieldStreet, jTextFieldBarangay, jTextFieldCity, jTextFieldProvince, jTextFieldCountry, jTextFieldEmgFname, jTextFieldEmgLname, jTextFieldEmgPhoneX, jTextFieldEmgPhoneY, jTextFieldEmgPhoneZ};
        JDateChooser[] dateArray = {jDateChooserDob};
        JComboBox[] comboArray = {jComboBoxBlood, jComboBoxCountryCode, jComboBoxEmgCountryCode};
        ButtonGroup[] buttonArray = {buttonGroupSex};
        
        RecordAdder ra = new RecordAdder();
        if (ra.addPatient(this, textArray, dateArray, comboArray, buttonArray, imagePath)) {
            JOptionPane.showMessageDialog(this, "Patient Added Successfully");
        }else {
            JOptionPane.showMessageDialog(this, "Account Not Added. Something Went Wrong :(");
        }

//        CreateAccountLogic cal = new CreateAccountLogic(textArray, dateArray, comboArray, buttonArray, imagePath);
//        cal.ca = this;
//        
//
//        if(!cal.isEmpty() && !cal.isUsernameExist()) {
//            Boolean status = cal.createNewAccount();
//
//            if (status) {
//                JOptionPane.showMessageDialog(this, "Account Created");
//            }else {
//                JOptionPane.showMessageDialog(this, "Something went wrong :(");
//            }
//        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    public void highlightEmptyFields(Boolean[] emptyFields, int i) {
        System.out.println("There is an empty field!" + " " + i);
    }
    
    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jTextFieldPhoneXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneXFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneXFocusGained

    private void jTextFieldPhoneXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneXFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneXFocusLost

    private void jTextFieldPhoneYFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneYFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneYFocusGained

    private void jTextFieldPhoneYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneYFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneYFocusLost

    private void jTextFieldPhoneZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneZFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneZFocusGained

    private void jTextFieldPhoneZFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneZFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneZFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSex;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBoxBlood;
    private javax.swing.JComboBox<String> jComboBoxCountryCode;
    private javax.swing.JComboBox<String> jComboBoxEmgCountryCode;
    private com.toedter.calendar.JDateChooser jDateChooserDob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBarangay;
    private javax.swing.JLabel jLabelBlood;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelDob;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPhone1;
    private javax.swing.JLabel jLabelPic;
    private javax.swing.JLabel jLabelPicName;
    private javax.swing.JLabel jLabelProvince;
    private javax.swing.JLabel jLabelSex;
    private javax.swing.JLabel jLabelStreet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonOther;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBarangay;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmgFname;
    private javax.swing.JTextField jTextFieldEmgLname;
    private javax.swing.JTextField jTextFieldEmgPhoneX;
    private javax.swing.JTextField jTextFieldEmgPhoneY;
    private javax.swing.JTextField jTextFieldEmgPhoneZ;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldMname;
    private javax.swing.JTextField jTextFieldPhoneX;
    private javax.swing.JTextField jTextFieldPhoneY;
    private javax.swing.JTextField jTextFieldPhoneZ;
    private javax.swing.JTextField jTextFieldProvince;
    private javax.swing.JTextField jTextFieldStreet;
    // End of variables declaration//GEN-END:variables
}
