
package gui;


public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jPanelControl = new javax.swing.JPanel();
        jLabelAppName = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelSlogan = new javax.swing.JLabel();
        jPanelPatient = new javax.swing.JPanel();
        jLabelPatient = new javax.swing.JLabel();
        jPanelPhysician = new javax.swing.JPanel();
        jLabelPhysician = new javax.swing.JLabel();
        jPanelSchedule = new javax.swing.JPanel();
        jLabelSchedule = new javax.swing.JLabel();
        jPanelManual = new javax.swing.JPanel();
        jLabelManual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);

        jPanelBackground.setBackground(new java.awt.Color(204, 255, 255));
        jPanelBackground.setMaximumSize(new java.awt.Dimension(645, 425));
        jPanelBackground.setMinimumSize(new java.awt.Dimension(645, 425));

        jPanelControl.setBackground(new java.awt.Color(51, 153, 255));
        jPanelControl.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanelControl.setMinimumSize(new java.awt.Dimension(100, 25));
        jPanelControl.setPreferredSize(new java.awt.Dimension(539, 25));

        jLabelAppName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelAppName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAppName.setText("Patient Monitoring System");

        jLabelMinimize.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setText("-");
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        jLabelExit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("x");
        jLabelExit.setMaximumSize(new java.awt.Dimension(8, 25));
        jLabelExit.setMinimumSize(new java.awt.Dimension(8, 25));
        jLabelExit.setPreferredSize(new java.awt.Dimension(8, 25));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
        jPanelControl.setLayout(jPanelControlLayout);
        jPanelControlLayout.setHorizontalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelAppName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelControlLayout.setVerticalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAppName))
                .addContainerGap())
        );

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/placeholder-logo.png"))); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabelTitle.setText("General Hospital");

        jLabelSlogan.setText("Lorem ipsum dolor sit ametelit. Aliquam eget.");

        jPanelPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPatientMouseClicked(evt);
            }
        });

        jLabelPatient.setText("Patient List");

        javax.swing.GroupLayout jPanelPatientLayout = new javax.swing.GroupLayout(jPanelPatient);
        jPanelPatient.setLayout(jPanelPatientLayout);
        jPanelPatientLayout.setHorizontalGroup(
            jPanelPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPatientLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabelPatient)
                .addGap(86, 86, 86))
        );
        jPanelPatientLayout.setVerticalGroup(
            jPanelPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPatientLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabelPatient)
                .addGap(31, 31, 31))
        );

        jPanelPhysician.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPhysicianMouseClicked(evt);
            }
        });

        jLabelPhysician.setText("Physician List");

        javax.swing.GroupLayout jPanelPhysicianLayout = new javax.swing.GroupLayout(jPanelPhysician);
        jPanelPhysician.setLayout(jPanelPhysicianLayout);
        jPanelPhysicianLayout.setHorizontalGroup(
            jPanelPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhysicianLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelPhysician)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPhysicianLayout.setVerticalGroup(
            jPanelPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhysicianLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPhysician)
                .addGap(15, 15, 15))
        );

        jPanelSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelScheduleMouseClicked(evt);
            }
        });

        jLabelSchedule.setText("Physician List");

        javax.swing.GroupLayout jPanelScheduleLayout = new javax.swing.GroupLayout(jPanelSchedule);
        jPanelSchedule.setLayout(jPanelScheduleLayout);
        jPanelScheduleLayout.setHorizontalGroup(
            jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScheduleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelSchedule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelScheduleLayout.setVerticalGroup(
            jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScheduleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSchedule)
                .addContainerGap())
        );

        jPanelManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelManualMouseClicked(evt);
            }
        });

        jLabelManual.setText("Physician List");

        javax.swing.GroupLayout jPanelManualLayout = new javax.swing.GroupLayout(jPanelManual);
        jPanelManual.setLayout(jPanelManualLayout);
        jPanelManualLayout.setHorizontalGroup(
            jPanelManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManualLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabelManual)
                .addGap(69, 69, 69))
        );
        jPanelManualLayout.setVerticalGroup(
            jPanelManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManualLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabelManual)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelControl, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabelLogo)
                        .addGap(41, 41, 41)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTitle)
                            .addComponent(jLabelSlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelPhysician, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabelTitle)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSlogan))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLogo)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPhysician, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jPanelPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPatientMouseClicked
        PatientFrame patientFrame = new PatientFrame();
        patientFrame.setLocationRelativeTo(null);
        patientFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelPatientMouseClicked

    private void jPanelPhysicianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPhysicianMouseClicked
        PhysicianFrame physicianFrame = new PhysicianFrame();
        physicianFrame.setLocationRelativeTo(null);
        physicianFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelPhysicianMouseClicked

    private void jPanelScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelScheduleMouseClicked
        ScheduleForm scheduleForm = new ScheduleForm();
        scheduleForm.setLocationRelativeTo(null);
        scheduleForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelScheduleMouseClicked

    private void jPanelManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelManualMouseClicked
        ManualForm manualForm = new ManualForm();
        manualForm.setLocationRelativeTo(null);
        manualForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelManualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAppName;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelManual;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelPatient;
    private javax.swing.JLabel jLabelPhysician;
    private javax.swing.JLabel jLabelSchedule;
    private javax.swing.JLabel jLabelSlogan;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelManual;
    private javax.swing.JPanel jPanelPatient;
    private javax.swing.JPanel jPanelPhysician;
    private javax.swing.JPanel jPanelSchedule;
    // End of variables declaration//GEN-END:variables
}
