
package gui.admin;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import logic.ImageHandler;
import logic.Patient;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import logic.PatientConditionCRUD;
import logic.TableHandler;
import logic.AddPerson;

public class DetailedPatientFrame extends javax.swing.JFrame {

    public static int id;
    Patient patient;
    Boolean addingMedCon = false;
    Timer timer;
    int health_id;
    Boolean hidden = true;
    String imagePath;
    /**
     * Creates new form DetailedPatientFrame
     */
    public DetailedPatientFrame() {
        initComponents();
        populateInfo();
        hideEditField();
//        populateMedicalCondition();
        populateTables();
        jRadioButtonMale.setActionCommand("Male");
        jRadioButtonFemale.setActionCommand("Female");
        jRadioButtonOther.setActionCommand("Other");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSex = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabelDob = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelDob1 = new javax.swing.JLabel();
        jLabelDob2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelDob3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelDob9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelDob10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelDob11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabelDob12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabelStreet = new javax.swing.JLabel();
        jTextFieldStreet = new javax.swing.JTextField();
        jLabelBarangay = new javax.swing.JLabel();
        jTextFieldBarangay = new javax.swing.JTextField();
        jLabelCity = new javax.swing.JLabel();
        jTextFieldCity = new javax.swing.JTextField();
        jLabelProvince = new javax.swing.JLabel();
        jTextFieldProvince = new javax.swing.JTextField();
        jLabelCountry = new javax.swing.JLabel();
        jTextFieldCountry = new javax.swing.JTextField();
        jDateChooserDob = new com.toedter.calendar.JDateChooser();
        jComboBoxBlood = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBoxCountryCode = new javax.swing.JComboBox<>();
        jTextFieldPhoneX = new javax.swing.JTextField();
        jTextFieldPhoneY = new javax.swing.JTextField();
        jTextFieldPhoneZ = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldMname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jLabelSex = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonOther = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldEmgFname = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextFieldRelationship = new javax.swing.JTextField();
        jComboBoxEmgCountryCode = new javax.swing.JComboBox<>();
        jTextFieldEmgPhoneX = new javax.swing.JTextField();
        jTextFieldEmgPhoneY = new javax.swing.JTextField();
        jTextFieldEmgPhoneZ = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTextFieldEmgLname1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButtonDeletePatientRecord = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabelChangeImage = new javax.swing.JLabel();
        jLabelConfirmImage = new javax.swing.JLabel();
        jLabelResetImage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(530, 530));
        jPanel2.setLayout(null);

        jButton1.setText("View");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(220, 10, 72, 23);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Health Condition");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 60, 100, 16);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(10, 80, 240, 22);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Description");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 120, 100, 16);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Complication");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 250, 100, 16);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(10, 270, 240, 22);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Diagnosis Date");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(280, 60, 100, 16);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Severity");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(280, 120, 100, 16);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(280, 140, 152, 22);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Notes");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(280, 180, 100, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(280, 200, 240, 90);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(10, 140, 240, 90);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(140, 360, 75, 23);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(230, 360, 75, 23);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(280, 80, 150, 22);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(320, 360, 72, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 520, 530, 400);

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(530, 300));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(530, 300));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(530, 300));

        jPanel5.setAutoscrolls(true);
        jPanel5.setMaximumSize(new java.awt.Dimension(530, 630));
        jPanel5.setMinimumSize(new java.awt.Dimension(530, 630));
        jPanel5.setPreferredSize(new java.awt.Dimension(530, 700));
        jPanel5.setLayout(null);

        jLabelDob.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDob.setText("Date of Birth:");
        jPanel5.add(jLabelDob);
        jLabelDob.setBounds(40, 300, 69, 16);

        jLabel12.setText("n/a");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(130, 300, 130, 16);

        jLabelDob1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDob1.setText("Blood type:");
        jPanel5.add(jLabelDob1);
        jLabelDob1.setBounds(50, 270, 60, 16);

        jLabelDob2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDob2.setText("Phone:");
        jPanel5.add(jLabelDob2);
        jLabelDob2.setBounds(70, 330, 40, 16);

        jLabel15.setText("n/a");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(130, 330, 220, 16);

        jLabelDob3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDob3.setText("Email:");
        jPanel5.add(jLabelDob3);
        jLabelDob3.setBounds(70, 360, 40, 16);

        jLabel16.setText("n/a");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(130, 360, 130, 16);
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(250, 50, 0, 3);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(120, 590, 10, 80);

        jLabelDob9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDob9.setText("Name");
        jPanel5.add(jLabelDob9);
        jLabelDob9.setBounds(40, 590, 70, 16);

        jLabel22.setText("n/a");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(130, 590, 260, 16);
        jPanel5.add(jSeparator3);
        jSeparator3.setBounds(30, 520, 490, 10);

        jLabelDob10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDob10.setText("Phone");
        jPanel5.add(jLabelDob10);
        jLabelDob10.setBounds(40, 620, 70, 16);

        jLabel23.setText("n/a");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(130, 620, 220, 16);

        jLabel1.setText("Emergency Contact Information");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(60, 540, 170, 16);

        jLabelDob11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDob11.setText("Relationship");
        jPanel5.add(jLabelDob11);
        jLabelDob11.setBounds(40, 650, 70, 16);

        jLabel24.setText("n/a");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(130, 650, 130, 16);

        jLabelDob12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDob12.setText("Address:");
        jPanel5.add(jLabelDob12);
        jLabelDob12.setBounds(60, 390, 50, 16);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("n/a");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel25.setAutoscrolls(true);
        jPanel5.add(jLabel25);
        jLabel25.setBounds(130, 390, 300, 50);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator5);
        jSeparator5.setBounds(120, 270, 10, 140);

        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("Edit");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel18);
        jLabel18.setBounds(10, 390, 40, 16);

        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("Edit");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel19);
        jLabel19.setBounds(10, 360, 40, 16);

        jLabelStreet.setText("Street");
        jPanel5.add(jLabelStreet);
        jLabelStreet.setBounds(140, 390, 30, 16);

        jTextFieldStreet.setText("Blk # Lot # Phase #");
        jTextFieldStreet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldStreetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldStreetFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldStreet);
        jTextFieldStreet.setBounds(130, 410, 140, 22);

        jLabelBarangay.setText("Barangay");
        jPanel5.add(jLabelBarangay);
        jLabelBarangay.setBounds(280, 390, 70, 16);

        jTextFieldBarangay.setText("Barangay #");
        jTextFieldBarangay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBarangayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBarangayFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldBarangay);
        jTextFieldBarangay.setBounds(270, 410, 120, 22);

        jLabelCity.setText("City");
        jPanel5.add(jLabelCity);
        jLabelCity.setBounds(400, 390, 21, 16);

        jTextFieldCity.setText("Dasmariñas City");
        jTextFieldCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCityFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldCity);
        jTextFieldCity.setBounds(390, 410, 110, 22);

        jLabelProvince.setText("Provice");
        jPanel5.add(jLabelProvince);
        jLabelProvince.setBounds(140, 440, 39, 16);

        jTextFieldProvince.setText("Cavite");
        jTextFieldProvince.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProvinceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProvinceFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldProvince);
        jTextFieldProvince.setBounds(130, 460, 100, 22);

        jLabelCountry.setText("Country:");
        jPanel5.add(jLabelCountry);
        jLabelCountry.setBounds(240, 440, 46, 16);

        jTextFieldCountry.setText("Philippines");
        jTextFieldCountry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCountryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCountryFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldCountry);
        jTextFieldCountry.setBounds(230, 460, 125, 22);

        jDateChooserDob.setDateFormatString("MMMMMMMMM d, y");
        jPanel5.add(jDateChooserDob);
        jDateChooserDob.setBounds(130, 300, 130, 22);

        jComboBoxBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O-", "O+", "B-", "B+", "A-", "A+", "AB-", "AB+" }));
        jComboBoxBlood.setSelectedIndex(-1);
        jComboBoxBlood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxBloodMouseClicked(evt);
            }
        });
        jPanel5.add(jComboBoxBlood);
        jComboBoxBlood.setBounds(130, 270, 80, 22);

        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("Edit");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel20);
        jLabel20.setBounds(10, 270, 40, 16);

        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("Edit");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel21);
        jLabel21.setBounds(10, 300, 40, 16);

        jLabel26.setForeground(new java.awt.Color(0, 0, 255));
        jLabel26.setText("Edit");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel26);
        jLabel26.setBounds(10, 330, 40, 16);

        jComboBoxCountryCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+63" }));
        jPanel5.add(jComboBoxCountryCode);
        jComboBoxCountryCode.setBounds(130, 330, 60, 22);

        jTextFieldPhoneX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneX.setText("XXX");
        jTextFieldPhoneX.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneX.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneX.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneXFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldPhoneX);
        jTextFieldPhoneX.setBounds(200, 330, 40, 20);

        jTextFieldPhoneY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneY.setText("YYY");
        jTextFieldPhoneY.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneY.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneY.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneYFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneYFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldPhoneY);
        jTextFieldPhoneY.setBounds(250, 330, 40, 20);

        jTextFieldPhoneZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneZ.setText("ZZZZ");
        jTextFieldPhoneZ.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneZ.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneZ.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldPhoneZ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneZFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneZFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldPhoneZ);
        jTextFieldPhoneZ.setBounds(300, 330, 50, 20);

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(130, 360, 130, 22);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("(");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(190, 330, 10, 20);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText(")");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(240, 330, 10, 20);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("-");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(290, 330, 10, 20);

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setOpaque(true);
        jPanel5.add(jLabel6);
        jLabel6.setBounds(130, 50, 80, 80);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Name");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(40, 170, 70, 16);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Age");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(40, 200, 70, 16);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Sex");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(40, 230, 70, 16);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Patient no.");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(40, 140, 70, 16);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator6);
        jSeparator6.setBounds(120, 140, 10, 110);

        jLabel32.setText("n/a");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(140, 230, 160, 16);

        jLabel33.setText("n/a");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(140, 140, 160, 16);

        jLabel34.setText("n/a");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(140, 170, 160, 16);

        jLabel35.setText("n/a");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(140, 200, 160, 16);

        jLabel36.setForeground(new java.awt.Color(0, 0, 255));
        jLabel36.setText("Edit");
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel36);
        jLabel36.setBounds(10, 230, 40, 16);

        jLabel38.setForeground(new java.awt.Color(0, 0, 255));
        jLabel38.setText("Edit");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel38);
        jLabel38.setBounds(10, 170, 40, 16);

        jLabel4.setText("First name:");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(130, 160, 70, 16);

        jTextFieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFnameActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldFname);
        jTextFieldFname.setBounds(130, 180, 130, 22);

        jLabel10.setText("Middle name:");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(260, 160, 80, 16);

        jTextFieldMname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMnameActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldMname);
        jTextFieldMname.setBounds(260, 180, 130, 22);

        jLabel17.setText("Last name:");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(390, 160, 70, 16);

        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldLname);
        jTextFieldLname.setBounds(390, 180, 130, 22);

        jLabelSex.setText("Sex:");
        jPanel5.add(jLabelSex);
        jLabelSex.setBounds(140, 220, 20, 16);

        buttonGroupSex.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButtonMale);
        jRadioButtonMale.setBounds(130, 240, 50, 21);

        buttonGroupSex.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");
        jPanel5.add(jRadioButtonFemale);
        jRadioButtonFemale.setBounds(190, 240, 70, 21);

        buttonGroupSex.add(jRadioButtonOther);
        jRadioButtonOther.setText("Other");
        jPanel5.add(jRadioButtonOther);
        jRadioButtonOther.setBounds(260, 240, 60, 21);

        jLabel14.setText("jLabel14");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(130, 270, 43, 16);

        jLabel37.setText("First name");
        jPanel5.add(jLabel37);
        jLabel37.setBounds(130, 570, 70, 16);

        jTextFieldEmgFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmgFnameActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldEmgFname);
        jTextFieldEmgFname.setBounds(130, 590, 130, 22);

        jLabel39.setText("Last name");
        jPanel5.add(jLabel39);
        jLabel39.setBounds(260, 570, 70, 16);

        jTextFieldRelationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRelationshipActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldRelationship);
        jTextFieldRelationship.setBounds(130, 650, 130, 22);

        jComboBoxEmgCountryCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+63" }));
        jPanel5.add(jComboBoxEmgCountryCode);
        jComboBoxEmgCountryCode.setBounds(130, 620, 60, 22);

        jTextFieldEmgPhoneX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmgPhoneX.setText("XXX");
        jTextFieldEmgPhoneX.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneX.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneX.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneXFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldEmgPhoneX);
        jTextFieldEmgPhoneX.setBounds(200, 620, 40, 20);

        jTextFieldEmgPhoneY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmgPhoneY.setText("YYY");
        jTextFieldEmgPhoneY.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneY.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneY.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneYFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneYFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldEmgPhoneY);
        jTextFieldEmgPhoneY.setBounds(250, 620, 40, 20);

        jTextFieldEmgPhoneZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmgPhoneZ.setText("ZZZZ");
        jTextFieldEmgPhoneZ.setMaximumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneZ.setMinimumSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneZ.setPreferredSize(new java.awt.Dimension(64, 17));
        jTextFieldEmgPhoneZ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneZFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmgPhoneZFocusLost(evt);
            }
        });
        jPanel5.add(jTextFieldEmgPhoneZ);
        jTextFieldEmgPhoneZ.setBounds(300, 620, 50, 20);

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("(");
        jPanel5.add(jLabel40);
        jLabel40.setBounds(190, 620, 10, 20);

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText(")");
        jPanel5.add(jLabel41);
        jLabel41.setBounds(240, 620, 10, 20);

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("-");
        jPanel5.add(jLabel42);
        jLabel42.setBounds(290, 620, 10, 20);

        jTextFieldEmgLname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmgLname1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldEmgLname1);
        jTextFieldEmgLname1.setBounds(260, 590, 130, 22);

        jLabel43.setForeground(new java.awt.Color(0, 0, 255));
        jLabel43.setText("Edit");
        jLabel43.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel43);
        jLabel43.setBounds(10, 590, 40, 16);

        jLabel44.setForeground(new java.awt.Color(0, 0, 255));
        jLabel44.setText("Edit");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel44);
        jLabel44.setBounds(10, 620, 40, 16);

        jLabel45.setForeground(new java.awt.Color(0, 0, 255));
        jLabel45.setText("Edit");
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel45);
        jLabel45.setBounds(10, 650, 40, 16);

        jButtonDeletePatientRecord.setText("Delete Patient Record");
        jButtonDeletePatientRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePatientRecordActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonDeletePatientRecord);
        jButtonDeletePatientRecord.setBounds(330, 40, 143, 23);

        jLabel46.setForeground(new java.awt.Color(0, 153, 0));
        jLabel46.setText("Submit");
        jLabel46.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel46);
        jLabel46.setBounds(270, 300, 40, 16);

        jLabel47.setForeground(new java.awt.Color(0, 153, 0));
        jLabel47.setText("Submit");
        jLabel47.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel47);
        jLabel47.setBounds(460, 210, 40, 16);

        jLabel48.setForeground(new java.awt.Color(0, 153, 0));
        jLabel48.setText("Submit");
        jLabel48.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel48);
        jLabel48.setBounds(320, 240, 40, 16);

        jLabel49.setForeground(new java.awt.Color(0, 153, 0));
        jLabel49.setText("Submit");
        jLabel49.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel49);
        jLabel49.setBounds(270, 360, 40, 16);

        jLabel50.setForeground(new java.awt.Color(0, 153, 0));
        jLabel50.setText("Submit");
        jLabel50.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel50);
        jLabel50.setBounds(360, 620, 40, 16);

        jLabel51.setForeground(new java.awt.Color(0, 153, 0));
        jLabel51.setText("Submit");
        jLabel51.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel51);
        jLabel51.setBounds(220, 270, 40, 16);

        jLabel52.setForeground(new java.awt.Color(0, 153, 0));
        jLabel52.setText("Submit");
        jLabel52.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel52);
        jLabel52.setBounds(370, 460, 40, 16);

        jLabel53.setForeground(new java.awt.Color(0, 153, 0));
        jLabel53.setText("Submit");
        jLabel53.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel53MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel53);
        jLabel53.setBounds(270, 650, 40, 16);

        jLabel54.setForeground(new java.awt.Color(0, 153, 0));
        jLabel54.setText("Submit");
        jLabel54.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel54);
        jLabel54.setBounds(400, 590, 40, 16);

        jLabel55.setForeground(new java.awt.Color(0, 153, 0));
        jLabel55.setText("Submit");
        jLabel55.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel55);
        jLabel55.setBounds(360, 330, 40, 16);

        jLabelChangeImage.setForeground(new java.awt.Color(0, 0, 255));
        jLabelChangeImage.setText("Change Image");
        jLabelChangeImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelChangeImageMouseClicked(evt);
            }
        });
        jPanel5.add(jLabelChangeImage);
        jLabelChangeImage.setBounds(40, 80, 90, 16);

        jLabelConfirmImage.setForeground(new java.awt.Color(0, 153, 0));
        jLabelConfirmImage.setText("Confirm");
        jLabelConfirmImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConfirmImageMouseClicked(evt);
            }
        });
        jPanel5.add(jLabelConfirmImage);
        jLabelConfirmImage.setBounds(220, 110, 70, 16);

        jLabelResetImage.setForeground(new java.awt.Color(255, 0, 0));
        jLabelResetImage.setText("Reset Image");
        jLabelResetImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelResetImageMouseClicked(evt);
            }
        });
        jPanel5.add(jLabelResetImage);
        jLabelResetImage.setBounds(220, 80, 70, 16);

        jScrollPane2.setViewportView(jPanel5);

        jTabbedPane1.addTab("Personal Information", jScrollPane2);

        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jTabbedPane1.addTab("Medical Condition", jScrollPane3);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 530, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateTables() {
        TableHandler tableHandler = new TableHandler();
        TableModel tableModel = tableHandler.getPatientCondition(id);
        jTable1.setModel(tableModel);
        if (jTable1.getRowCount() != 0) {
            TableColumn column0 = jTable1.getColumnModel().getColumn(0);
            column0.setMinWidth(0);
            column0.setMaxWidth(0);
            column0.setWidth(0);
            column0.setPreferredWidth(0);

            TableColumn column7 = jTable1.getColumnModel().getColumn(7);
            column7.setMinWidth(0);
            column7.setMaxWidth(0);
            column7.setWidth(0);
            column7.setPreferredWidth(0);
        }
    }
    
    private void hideEditField() {
        jLabelResetImage.setVisible(false);
        jLabelConfirmImage.setVisible(false);
        
        jComboBoxBlood.setVisible(false);
        
        jDateChooserDob.setVisible(false);
        
        jComboBoxCountryCode.setVisible(false);
        jLabel27.setVisible(false);
        jTextFieldPhoneX.setVisible(false);
        jLabel28.setVisible(false);
        jTextFieldPhoneY.setVisible(false);
        jLabel29.setVisible(false);
        jTextFieldPhoneZ.setVisible(false);
        
        jTextFieldEmail.setVisible(false);
        
        jLabelStreet.setVisible(false);
        jTextFieldStreet.setVisible(false);
        jLabelBarangay.setVisible(false);
        jTextFieldBarangay.setVisible(false);
        jLabelCity.setVisible(false);
        jTextFieldCity.setVisible(false);
        jLabelProvince.setVisible(false);
        jTextFieldProvince.setVisible(false);
        jLabelCountry.setVisible(false);
        jTextFieldCountry.setVisible(false);
        
        
        jLabel4.setVisible(false);
        jLabel10.setVisible(false);
        jLabel17.setVisible(false);
        jTextFieldFname.setVisible(false);
        jTextFieldMname.setVisible(false);
        jTextFieldLname.setVisible(false);
        
        
        jLabelSex.setVisible(false);
        jRadioButtonMale.setVisible(false);
        jRadioButtonFemale.setVisible(false);
        jRadioButtonOther.setVisible(false);
        
        
        jLabel37.setVisible(false);
        jLabel39.setVisible(false);
        jTextFieldEmgFname.setVisible(false);
        jTextFieldEmgLname1.setVisible(false);
        
        
        jComboBoxEmgCountryCode.setVisible(false);
        jLabel40.setVisible(false);
        jTextFieldEmgPhoneX.setVisible(false);
        jLabel41.setVisible(false);
        jTextFieldEmgPhoneY.setVisible(false);
        jLabel42.setVisible(false);
        jTextFieldEmgPhoneZ.setVisible(false);
        
        
        jTextFieldRelationship.setVisible(false);
        
        
        
        jLabel47.setVisible(false);
        jLabel48.setVisible(false);
        jLabel51.setVisible(false);
        jLabel46.setVisible(false);
        jLabel55.setVisible(false);
        jLabel49.setVisible(false);
        jLabel52.setVisible(false);
        jLabel54.setVisible(false);
        jLabel50.setVisible(false);
        jLabel53.setVisible(false);

    }
    
    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        if (jLabel25.isVisible()) {
            jLabel25.setVisible(false);
            jLabelStreet.setVisible(true);
            jTextFieldStreet.setVisible(true);
            jLabelBarangay.setVisible(true);
            jTextFieldBarangay.setVisible(true);
            jLabelCity.setVisible(true);
            jTextFieldCity.setVisible(true);
            jLabelProvince.setVisible(true);
            jTextFieldProvince.setVisible(true);
            jLabelCountry.setVisible(true);
            jTextFieldCountry.setVisible(true);
            jLabel52.setVisible(true);
            jLabel18.setText("Cancel");
            jLabel18.setForeground(Color.RED);
        }else {
            jLabel25.setVisible(true);
            jLabelStreet.setVisible(false);
            jTextFieldStreet.setVisible(false);
            jLabelBarangay.setVisible(false);
            jTextFieldBarangay.setVisible(false);
            jLabelCity.setVisible(false);
            jTextFieldCity.setVisible(false);
            jLabelProvince.setVisible(false);
            jTextFieldProvince.setVisible(false);
            jLabelCountry.setVisible(false);
            jTextFieldCountry.setVisible(false);
            jLabel52.setVisible(false);
            jLabel18.setText("Edit");
            jLabel18.setForeground(Color.BLUE);
        }
        
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jTextFieldStreetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStreetFocusGained
        if (jTextFieldStreet.getText().equals("Blk # Lot # Phase #")) {
            jTextFieldStreet.setText("");
        }
    }//GEN-LAST:event_jTextFieldStreetFocusGained

    private void jTextFieldStreetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStreetFocusLost
        if (jTextFieldStreet.getText().isEmpty()) {
            jTextFieldStreet.setText("Blk # Lot # Phase #");
        }
    }//GEN-LAST:event_jTextFieldStreetFocusLost

    private void jTextFieldBarangayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBarangayFocusGained
        if (jTextFieldBarangay.getText().equals("Barangay #")) {
            jTextFieldBarangay.setText("");
        }
    }//GEN-LAST:event_jTextFieldBarangayFocusGained

    private void jTextFieldBarangayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBarangayFocusLost
        if (jTextFieldBarangay.getText().isEmpty()) {
            jTextFieldBarangay.setText("Barangay #");
        }
    }//GEN-LAST:event_jTextFieldBarangayFocusLost

    private void jTextFieldCityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCityFocusGained
        if (jTextFieldCity.getText().equals("Dasmariñas City")) {
            jTextFieldCity.setText("");
        }
    }//GEN-LAST:event_jTextFieldCityFocusGained

    private void jTextFieldCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCityFocusLost
        if (jTextFieldCity.getText().isEmpty()) {
            jTextFieldCity.setText("Dasmariñas City");
        }
    }//GEN-LAST:event_jTextFieldCityFocusLost

    private void jTextFieldProvinceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProvinceFocusGained
        if (jTextFieldProvince.getText().equals("Cavite")) {
            jTextFieldProvince.setText("");
        }
    }//GEN-LAST:event_jTextFieldProvinceFocusGained

    private void jTextFieldProvinceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProvinceFocusLost
        if (jTextFieldProvince.getText().isEmpty()) {
            jTextFieldProvince.setText("Cavite");
        }
    }//GEN-LAST:event_jTextFieldProvinceFocusLost

    private void jTextFieldCountryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCountryFocusGained
        if (jTextFieldCountry.getText().equals("Philippines")) {
            jTextFieldCountry.setText("");
        }
    }//GEN-LAST:event_jTextFieldCountryFocusGained

    private void jTextFieldCountryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCountryFocusLost
        if (jTextFieldCountry.getText().isEmpty()) {
            jTextFieldCountry.setText("Philippines");
        }
    }//GEN-LAST:event_jTextFieldCountryFocusLost

    private void jComboBoxBloodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBloodMouseClicked
        
    }//GEN-LAST:event_jComboBoxBloodMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if (jLabel16.isVisible()) {
            jLabel16.setVisible(false);
            jTextFieldEmail.setVisible(true);
            jLabel49.setVisible(true);
            jLabel19.setText("Cancel");
            jLabel19.setForeground(Color.RED);
        }else {
            jLabel16.setVisible(true);
            jTextFieldEmail.setVisible(false);
            jLabel49.setVisible(false);
            jLabel19.setText("Edit");
            jLabel19.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        if (jLabel14.isVisible()) {
            jLabel14.setVisible(false);
            jComboBoxBlood.setVisible(true);
            jLabel51.setVisible(true);
            jLabel20.setText("Cancel");
            jLabel20.setForeground(Color.RED);
        }else {
            jLabel14.setVisible(true);
            jComboBoxBlood.setVisible(false);
            jLabel51.setVisible(false);
            jLabel20.setText("Edit");
            jLabel20.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        if (jLabel12.isVisible()) {
            jLabel12.setVisible(false);
            jDateChooserDob.setVisible(true);
            jLabel46.setVisible(true);
            jLabel21.setText("Cancel");
            jLabel21.setForeground(Color.RED);
        }else {
            jLabel12.setVisible(true);
            jDateChooserDob.setVisible(false);
            jLabel46.setVisible(false);
            jLabel21.setText("Edit");
            jLabel21.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        if (jLabel15.isVisible()) {
            jLabel15.setVisible(false);
            jComboBoxCountryCode.setVisible(true);
            jLabel27.setVisible(true);
            jTextFieldPhoneX.setVisible(true);
            jLabel28.setVisible(true);
            jTextFieldPhoneY.setVisible(true);
            jLabel29.setVisible(true);
            jTextFieldPhoneZ.setVisible(true);
            jLabel55.setVisible(true);
            jLabel26.setText("Cancel");
            jLabel26.setForeground(Color.RED);
        }else {
            jLabel15.setVisible(true);
            jComboBoxCountryCode.setVisible(false);
            jLabel27.setVisible(false);
            jTextFieldPhoneX.setVisible(false);
            jLabel28.setVisible(false);
            jTextFieldPhoneY.setVisible(false);
            jLabel29.setVisible(false);
            jTextFieldPhoneZ.setVisible(false);
            jLabel55.setVisible(false);
            jLabel26.setText("Edit");
            jLabel26.setForeground(Color.BLUE);
        }
        
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jTextFieldPhoneXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneXFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneXFocusGained

    private void jTextFieldPhoneXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneXFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneXFocusLost

    private void jTextFieldPhoneYFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneYFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneYFocusGained

    private void jTextFieldPhoneYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneYFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneYFocusLost

    private void jTextFieldPhoneZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneZFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneZFocusGained

    private void jTextFieldPhoneZFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneZFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneZFocusLost

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        
        
        if (hidden) {
            hidden = false;

            timer = new Timer(1, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    jPanel2.setLocation(jPanel2.getX(), jPanel2.getY() - 5);
                    if (jPanel2.getY() <= 160) {
                        timer.stop();
                    }
                }
            });
            timer.start();
        } else {
            hidden = true;

            timer = new Timer(1, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    jPanel2.setLocation(jPanel2.getX(), jPanel2.getY() + 5);
                    if (jPanel2.getY() >= 520) {
                        timer.stop();
                    }
                }
            });
            timer.start();
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        
        health_id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        jTextField1.setText(jTable1.getValueAt(selectedRow, 1).toString());
        jTextArea2.setText(jTable1.getValueAt(selectedRow, 2).toString());
        jTextField4.setText(jTable1.getValueAt(selectedRow, 3).toString());
        
        String dateString = jTable1.getValueAt(selectedRow, 4).toString();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = null;
        
        try {
            date = dateFormat.parse(dateString);
        } catch (ParseException ex) {
            Logger.getLogger(DetailedPatientFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jDateChooser1.setDate(date);
        jTextField7.setText(jTable1.getValueAt(selectedRow, 5).toString());
        jTextArea1.setText(jTable1.getValueAt(selectedRow, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JTextField[] txtFldArry = {jTextField1, jTextField4, jTextField7};
        JTextArea[] txtAreaArry = {jTextArea2, jTextArea1};
        
        PatientConditionCRUD pca = new PatientConditionCRUD(txtFldArry, txtAreaArry, jDateChooser1, id, health_id);
        if (pca.AddHealthCondition()) {
            JOptionPane.showMessageDialog(null, "Patient Condition Added");
        }else {
            JOptionPane.showMessageDialog(null, "Something Went Wrong");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JTextField[] txtFldArry = {jTextField1, jTextField4, jTextField7};
        JTextArea[] txtAreaArry = {jTextArea2, jTextArea1};
        
        PatientConditionCRUD pccrud = new PatientConditionCRUD(txtFldArry, txtAreaArry, jDateChooser1, id, health_id);
        if (pccrud.UpdateHealthCondition()) {
            JOptionPane.showMessageDialog(null, "Patient Condition Updated");
        } else {
            JOptionPane.showMessageDialog(null, "Something Went Wrong");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PatientConditionCRUD pccrud = new PatientConditionCRUD(null, null, null, 0, health_id);
        if (pccrud.DeleteHealthCondition()) {
            JOptionPane.showMessageDialog(null, "Patient Condition Deleted");
        } else {
            JOptionPane.showMessageDialog(null, "Something Went Wrong");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        if (jLabel32.isVisible()) {
            jLabel32.setVisible(false);
            jLabelSex.setVisible(true);
            jRadioButtonMale.setVisible(true);
            jRadioButtonFemale .setVisible(true);
            jRadioButtonOther.setVisible(true);
            jLabel48.setVisible(true);
            jLabel36.setText("Cancel");
            jLabel36.setForeground(Color.RED);
        }else {
            jLabel32.setVisible(true);
            jLabelSex.setVisible(false);
            jRadioButtonMale.setVisible(false);
            jRadioButtonFemale .setVisible(false);
            jRadioButtonOther.setVisible(false);
            jLabel48.setVisible(false);
            jLabel36.setText("Edit");
            jLabel36.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        if (jLabel34.isVisible()) {
            jLabel34.setVisible(false);
            jLabel4.setVisible(true);
            jLabel10.setVisible(true);
            jLabel17 .setVisible(true);
            jTextFieldFname.setVisible(true);
            jTextFieldMname .setVisible(true);
            jTextFieldLname.setVisible(true);
            jLabel47.setVisible(true);
            jLabel38.setText("Cancel");
            jLabel38.setForeground(Color.RED);
        }else {
            jLabel34.setVisible(true);
            jLabel4.setVisible(false);
            jLabel10.setVisible(false);
            jLabel17 .setVisible(false);
            jTextFieldFname.setVisible(false);
            jTextFieldMname .setVisible(false);
            jTextFieldLname.setVisible(false);
            jLabel47.setVisible(false);
            jLabel38.setText("Edit");
            jLabel38.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jTextFieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFnameActionPerformed

    private void jTextFieldMnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMnameActionPerformed

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jTextFieldEmgFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmgFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmgFnameActionPerformed

    private void jTextFieldRelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRelationshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRelationshipActionPerformed

    private void jTextFieldEmgPhoneXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneXFocusGained
        if (jTextFieldEmgPhoneX.getText().equals("XXX")) {
            jTextFieldEmgPhoneX.setText("");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneXFocusGained

    private void jTextFieldEmgPhoneXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneXFocusLost
        if (jTextFieldEmgPhoneX.getText().isEmpty()) {
            jTextFieldEmgPhoneX.setText("XXX");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneXFocusLost

    private void jTextFieldEmgPhoneYFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneYFocusGained
        if (jTextFieldEmgPhoneY.getText().equals("YYY")) {
            jTextFieldEmgPhoneY.setText("");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneYFocusGained

    private void jTextFieldEmgPhoneYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneYFocusLost
        if (jTextFieldEmgPhoneY.getText().isEmpty()) {
            jTextFieldEmgPhoneY.setText("YYY");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneYFocusLost

    private void jTextFieldEmgPhoneZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneZFocusGained
        if (jTextFieldEmgPhoneZ.getText().equals("ZZZZ")) {
            jTextFieldEmgPhoneZ.setText("");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneZFocusGained

    private void jTextFieldEmgPhoneZFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmgPhoneZFocusLost
        if (jTextFieldEmgPhoneZ.getText().isEmpty()) {
            jTextFieldEmgPhoneZ.setText("ZZZZ");
        }
    }//GEN-LAST:event_jTextFieldEmgPhoneZFocusLost

    private void jTextFieldEmgLname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmgLname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmgLname1ActionPerformed

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        if (jLabel22.isVisible()) {
            jLabel22.setVisible(false);
            jLabel37.setVisible(true);
            jLabel39.setVisible(true);
            jTextFieldEmgFname.setVisible(true);
            jTextFieldEmgLname1.setVisible(true);
            jLabel54.setVisible(true);
            jLabel43.setText("Cancel");
            jLabel43.setForeground(Color.RED);
        } else {
            jLabel22.setVisible(true);
            jLabel37.setVisible(false);
            jLabel39.setVisible(false);
            jTextFieldEmgFname.setVisible(false);
            jTextFieldEmgLname1.setVisible(false);
            jLabel54.setVisible(false);
            jLabel43.setText("Edit");
            jLabel43.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        if (jLabel23.isVisible()) {
            jLabel23.setVisible(false);
            jComboBoxEmgCountryCode.setVisible(true);
            jLabel40.setVisible(true);
            jTextFieldEmgPhoneX.setVisible(true);
            jLabel41.setVisible(true);
            jTextFieldEmgPhoneY.setVisible(true);
            jLabel42.setVisible(true);
            jTextFieldEmgPhoneZ.setVisible(true);
            jLabel50.setVisible(true);
            jLabel44.setText("Cancel");
            jLabel44.setForeground(Color.RED);
        } else {
            jLabel23.setVisible(true);
            jComboBoxEmgCountryCode.setVisible(false);
            jLabel40.setVisible(false);
            jTextFieldEmgPhoneX.setVisible(false);
            jLabel41.setVisible(false);
            jTextFieldEmgPhoneY.setVisible(false);
            jLabel42.setVisible(false);
            jTextFieldEmgPhoneZ.setVisible(false);
            jLabel50.setVisible(false);
            jLabel44.setText("Edit");
            jLabel44.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        if (jLabel24.isVisible()) {
            jLabel24.setVisible(false);
            jTextFieldRelationship.setVisible(true);
            jLabel53.setVisible(true);
            jLabel45.setText("Cancel");
            jLabel45.setForeground(Color.RED);
        } else {
            jLabel24.setVisible(true);
            jTextFieldRelationship.setVisible(false);
            jLabel53.setVisible(false);
            jLabel45.setText("Edit");
            jLabel45.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientBirthdate(jDateChooserDob, id)) {
            populateInfo();
            jLabel12.setVisible(true);
            jDateChooserDob.setVisible(false);
            jLabel46.setVisible(false);
            jLabel21.setText("Edit");
            jLabel21.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientName(jTextFieldFname, jTextFieldMname, jTextFieldLname, id)) {
            populateInfo();
            jLabel34.setVisible(true);
            jLabel4.setVisible(false);
            jLabel10.setVisible(false);
            jLabel17 .setVisible(false);
            jTextFieldFname.setVisible(false);
            jTextFieldMname .setVisible(false);
            jTextFieldLname.setVisible(false);
            jLabel47.setVisible(false);
            jLabel38.setText("Edit");
            jLabel38.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientSex(buttonGroupSex, id)) {
            populateInfo();
            jLabel32.setVisible(true);
            jLabelSex.setVisible(false);
            jRadioButtonMale.setVisible(false);
            jRadioButtonFemale .setVisible(false);
            jRadioButtonOther.setVisible(false);
            jLabel48.setVisible(false);
            jLabel36.setText("Edit");
            jLabel36.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel48MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientEmail(jTextFieldEmail, id)) {
            populateInfo();
            jLabel16.setVisible(true);
            jTextFieldEmail.setVisible(false);
            jLabel49.setVisible(false);
            jLabel19.setText("Edit");
            jLabel19.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel49MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientEmgPhone(jComboBoxEmgCountryCode, jTextFieldEmgPhoneX, jTextFieldEmgPhoneY, jTextFieldEmgPhoneZ, id)) {
            populateInfo();
            jLabel23.setVisible(true);
            jLabel40.setVisible(false);
            jLabel41.setVisible(false);
            jLabel42.setVisible(false);
            jComboBoxEmgCountryCode.setVisible(false);
            jLabel40.setVisible(false);
            jTextFieldEmgPhoneX.setVisible(false);
            jLabel41.setVisible(false);
            jTextFieldEmgPhoneY.setVisible(false);
            jLabel42.setVisible(false);
            jTextFieldEmgPhoneZ.setVisible(false);
            jLabel50.setVisible(false);
            jLabel44.setText("Edit");
            jLabel44.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientBlood(jComboBoxBlood, id)) {
            populateInfo();
            jLabel14.setVisible(true);
            jComboBoxBlood.setVisible(false);
            jLabel51.setVisible(false);
            jLabel20.setText("Edit");
            jLabel20.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientAdress(jTextFieldStreet, jTextFieldBarangay, jTextFieldCity, jTextFieldProvince, jTextFieldCountry, id)) {
            populateInfo();
            jLabel25.setVisible(true);
            jLabelStreet.setVisible(false);
            jLabelBarangay.setVisible(false);
            jLabelCity.setVisible(false);
            jLabelProvince.setVisible(false);
            jLabelCountry.setVisible(false);
            jTextFieldStreet.setVisible(false);
            jTextFieldBarangay.setVisible(false);
            jTextFieldCity.setVisible(false);
            jTextFieldProvince.setVisible(false);
            jTextFieldCountry.setVisible(false);
            
            jLabel52.setVisible(false);
            jLabel18.setText("Edit");
            jLabel18.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientRelationship(jTextFieldRelationship, id)) {
            populateInfo();
            jLabel24.setVisible(true);
            jTextFieldRelationship.setVisible(false);
            jLabel53.setVisible(false);
            jLabel45.setText("Edit");
            jLabel45.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel53MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientEmgName(jTextFieldEmgFname, jTextFieldEmgLname1, id)) {
            populateInfo();
            jLabel22.setVisible(true);
            jLabel37.setVisible(false);
            jLabel39.setVisible(false);
            jTextFieldEmgFname.setVisible(false);
            jTextFieldEmgLname1.setVisible(false);
            jLabel54.setVisible(false);
            jLabel43.setText("Edit");
            jLabel43.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientPhone(jComboBoxCountryCode, jTextFieldPhoneX, jTextFieldPhoneY, jTextFieldPhoneZ, id)) {
            populateInfo();
            jLabel15.setVisible(true);
            jLabel27.setVisible(false);
            jLabel28.setVisible(false);
            jLabel29.setVisible(false);
            jComboBoxCountryCode.setVisible(false);
            jTextFieldPhoneX.setVisible(false);
            jTextFieldPhoneY.setVisible(false);
            jTextFieldPhoneZ.setVisible(false);
            jLabel55.setVisible(false);
            jLabel26.setText("Edit");
            jLabel26.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jLabelChangeImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelChangeImageMouseClicked
        ImageHandler imageHandler = new ImageHandler();
        imagePath = imageHandler.browseImage(this);

        if (imagePath != null) {
            jLabel6.setIcon(imageHandler.resizeImage(jLabel6, null, imagePath));
            jLabelResetImage.setVisible(true);
            jLabelConfirmImage.setVisible(true);
        }
    }//GEN-LAST:event_jLabelChangeImageMouseClicked

    private void jLabelResetImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetImageMouseClicked
        populateInfo();
        jLabelResetImage.setVisible(false);
        jLabelConfirmImage.setVisible(false);
    }//GEN-LAST:event_jLabelResetImageMouseClicked

    private void jLabelConfirmImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConfirmImageMouseClicked
        AddPerson ap = new AddPerson();
        if (ap.updatePatientImage(imagePath, id)) {
            populateInfo();
            jLabelResetImage.setVisible(false);
            jLabelConfirmImage.setVisible(false);
        }
    }//GEN-LAST:event_jLabelConfirmImageMouseClicked

    private void jButtonDeletePatientRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePatientRecordActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Do you want to permanently delete this patient's record?");
        
        if (result == JOptionPane.YES_OPTION) {
            AddPerson pcrud = new AddPerson();
            if (pcrud.deleteRecord("patients", "id", id)) {
                JOptionPane.showMessageDialog(null, "Patient Record Deleted");
            } else {
                JOptionPane.showMessageDialog(null, "Something Went Wrong");
            }
        }
    }//GEN-LAST:event_jButtonDeletePatientRecordActionPerformed

    private void populateInfo() {
        patient = new Patient(id);
        ImageHandler imageHandler = new ImageHandler();
        jLabel6.setIcon(imageHandler.resizeImage(jLabel6, patient.getPic(), null));
        jLabel33.setText(String.valueOf(patient.getId()));
        jLabel34.setText(patient.getFirst_name() + " " + patient.getMname() + " " + patient.getLast_name());
        jLabel35.setText(String.valueOf(patient.getAge()) + " " + "years old");
        jLabel32.setText(patient.getSex());
        
        jLabel14.setText(patient.getBlood());
        SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM d, yyyy");
        jLabel12.setText(dateFormat.format(patient.getBirthdate()));
        jLabel15.setText(patient.getPhone());
        jLabel16.setText(patient.getEmail());
        //jLabel25.setText(patient.getStreet() + ", " + patient.getBarangay() + ", " + patient.getCity() + ", " + patient.getProvince() + ", " + patient.getCountry());
        jLabel25.setText("<html><body style='width: 300;word-wrap: break-word'>" + patient.getStreet() + ", " + patient.getBarangay() + ", " + patient.getCity() + ", " + patient.getProvince() + ", " + patient.getCountry() + "</body></html>");
        jLabel22.setText(patient.getEmg_fname() + " " + patient.getEmg_lname());
        jLabel23.setText(patient.getEmg_phone());
        jLabel24.setText(patient.getRelationship());
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailedPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailedPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailedPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailedPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailedPatientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonDeletePatientRecord;
    private javax.swing.JComboBox<String> jComboBoxBlood;
    private javax.swing.JComboBox<String> jComboBoxCountryCode;
    private javax.swing.JComboBox<String> jComboBoxEmgCountryCode;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooserDob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBarangay;
    private javax.swing.JLabel jLabelChangeImage;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelConfirmImage;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelDob;
    private javax.swing.JLabel jLabelDob1;
    private javax.swing.JLabel jLabelDob10;
    private javax.swing.JLabel jLabelDob11;
    private javax.swing.JLabel jLabelDob12;
    private javax.swing.JLabel jLabelDob2;
    private javax.swing.JLabel jLabelDob3;
    private javax.swing.JLabel jLabelDob9;
    private javax.swing.JLabel jLabelProvince;
    private javax.swing.JLabel jLabelResetImage;
    private javax.swing.JLabel jLabelSex;
    private javax.swing.JLabel jLabelStreet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonOther;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldBarangay;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmgFname;
    private javax.swing.JTextField jTextFieldEmgLname1;
    private javax.swing.JTextField jTextFieldEmgPhoneX;
    private javax.swing.JTextField jTextFieldEmgPhoneY;
    private javax.swing.JTextField jTextFieldEmgPhoneZ;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldMname;
    private javax.swing.JTextField jTextFieldPhoneX;
    private javax.swing.JTextField jTextFieldPhoneY;
    private javax.swing.JTextField jTextFieldPhoneZ;
    private javax.swing.JTextField jTextFieldProvince;
    private javax.swing.JTextField jTextFieldRelationship;
    private javax.swing.JTextField jTextFieldStreet;
    // End of variables declaration//GEN-END:variables
}
