
package gui.admin;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jPanelControl = new javax.swing.JPanel();
        jLabelAppName = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelSlogan = new javax.swing.JLabel();
        jPanelPatient = new javax.swing.JPanel();
        jLabelPatient = new javax.swing.JLabel();
        jPanelPhysician = new javax.swing.JPanel();
        jLabelPhysician = new javax.swing.JLabel();
        jPanelSchedule = new javax.swing.JPanel();
        jLabelSchedule = new javax.swing.JLabel();
        jPanelManual = new javax.swing.JPanel();
        jLabelManual = new javax.swing.JLabel();
        jPanelCreateAccount = new javax.swing.JPanel();
        jLabelCreateAccount = new javax.swing.JLabel();
        jPanelManual1 = new javax.swing.JPanel();
        jLabelManual1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);

        jPanelBackground.setBackground(new java.awt.Color(204, 255, 255));
        jPanelBackground.setMaximumSize(new java.awt.Dimension(645, 425));
        jPanelBackground.setMinimumSize(new java.awt.Dimension(645, 425));
        jPanelBackground.setLayout(null);

        jPanelControl.setBackground(new java.awt.Color(51, 153, 255));
        jPanelControl.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanelControl.setMinimumSize(new java.awt.Dimension(100, 25));
        jPanelControl.setPreferredSize(new java.awt.Dimension(539, 25));

        jLabelAppName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelAppName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAppName.setText("Patient Monitoring System");

        jLabelMinimize.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setText("-");
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        jLabelExit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("x");
        jLabelExit.setMaximumSize(new java.awt.Dimension(8, 25));
        jLabelExit.setMinimumSize(new java.awt.Dimension(8, 25));
        jLabelExit.setPreferredSize(new java.awt.Dimension(8, 25));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
        jPanelControl.setLayout(jPanelControlLayout);
        jPanelControlLayout.setHorizontalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelAppName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelControlLayout.setVerticalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAppName))
                .addContainerGap())
        );

        jPanelBackground.add(jPanelControl);
        jPanelControl.setBounds(0, 0, 645, 25);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/placeholder-logo.png"))); // NOI18N
        jPanelBackground.add(jLabelLogo);
        jLabelLogo.setBounds(107, 43, 126, 126);

        jLabelTitle.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabelTitle.setText("Administrator Panel");
        jPanelBackground.add(jLabelTitle);
        jLabelTitle.setBounds(266, 62, 338, 47);

        jLabelSlogan.setText("Lorem ipsum dolor sit ametelit. Aliquam eget.");
        jPanelBackground.add(jLabelSlogan);
        jLabelSlogan.setBounds(266, 127, 268, 16);

        jPanelPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPatientMouseClicked(evt);
            }
        });

        jLabelPatient.setText("Patient List");

        javax.swing.GroupLayout jPanelPatientLayout = new javax.swing.GroupLayout(jPanelPatient);
        jPanelPatient.setLayout(jPanelPatientLayout);
        jPanelPatientLayout.setHorizontalGroup(
            jPanelPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatientLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabelPatient)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanelPatientLayout.setVerticalGroup(
            jPanelPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPatientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPatient)
                .addGap(24, 24, 24))
        );

        jPanelBackground.add(jPanelPatient);
        jPanelPatient.setBounds(36, 175, 197, 100);

        jPanelPhysician.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPhysicianMouseClicked(evt);
            }
        });

        jLabelPhysician.setText("Employee List");

        javax.swing.GroupLayout jPanelPhysicianLayout = new javax.swing.GroupLayout(jPanelPhysician);
        jPanelPhysician.setLayout(jPanelPhysicianLayout);
        jPanelPhysicianLayout.setHorizontalGroup(
            jPanelPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhysicianLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelPhysician)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanelPhysicianLayout.setVerticalGroup(
            jPanelPhysicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhysicianLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPhysician)
                .addGap(15, 15, 15))
        );

        jPanelBackground.add(jPanelPhysician);
        jPanelPhysician.setBounds(251, 175, 166, 100);

        jPanelSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelScheduleMouseClicked(evt);
            }
        });

        jLabelSchedule.setText("Drug List");

        javax.swing.GroupLayout jPanelScheduleLayout = new javax.swing.GroupLayout(jPanelSchedule);
        jPanelSchedule.setLayout(jPanelScheduleLayout);
        jPanelScheduleLayout.setHorizontalGroup(
            jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScheduleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelSchedule)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanelScheduleLayout.setVerticalGroup(
            jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScheduleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSchedule)
                .addContainerGap())
        );

        jPanelBackground.add(jPanelSchedule);
        jPanelSchedule.setBounds(36, 287, 173, 124);

        jPanelManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelManualMouseClicked(evt);
            }
        });

        jLabelManual.setText("Room List");

        javax.swing.GroupLayout jPanelManualLayout = new javax.swing.GroupLayout(jPanelManual);
        jPanelManual.setLayout(jPanelManualLayout);
        jPanelManualLayout.setHorizontalGroup(
            jPanelManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManualLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelManual)
                .addGap(69, 69, 69))
        );
        jPanelManualLayout.setVerticalGroup(
            jPanelManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManualLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabelManual)
                .addGap(20, 20, 20))
        );

        jPanelBackground.add(jPanelManual);
        jPanelManual.setBounds(251, 287, 166, 124);

        jPanelCreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCreateAccountMouseClicked(evt);
            }
        });

        jLabelCreateAccount.setText("Create Account");

        javax.swing.GroupLayout jPanelCreateAccountLayout = new javax.swing.GroupLayout(jPanelCreateAccount);
        jPanelCreateAccount.setLayout(jPanelCreateAccountLayout);
        jPanelCreateAccountLayout.setHorizontalGroup(
            jPanelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCreateAccount)
                .addGap(69, 69, 69))
        );
        jPanelCreateAccountLayout.setVerticalGroup(
            jPanelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateAccountLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabelCreateAccount)
                .addGap(20, 20, 20))
        );

        jPanelBackground.add(jPanelCreateAccount);
        jPanelCreateAccount.setBounds(432, 175, 160, 100);

        jPanelManual1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelManual1MouseClicked(evt);
            }
        });

        jLabelManual1.setText("Manual");

        javax.swing.GroupLayout jPanelManual1Layout = new javax.swing.GroupLayout(jPanelManual1);
        jPanelManual1.setLayout(jPanelManual1Layout);
        jPanelManual1Layout.setHorizontalGroup(
            jPanelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManual1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelManual1)
                .addGap(69, 69, 69))
        );
        jPanelManual1Layout.setVerticalGroup(
            jPanelManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManual1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabelManual1)
                .addGap(20, 20, 20))
        );

        jPanelBackground.add(jPanelManual1);
        jPanelManual1.setBounds(430, 290, 160, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jPanelPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPatientMouseClicked
        PatientFrame patientFrame = new PatientFrame();
        patientFrame.setLocationRelativeTo(null);
        patientFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelPatientMouseClicked

    private void jPanelPhysicianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPhysicianMouseClicked
        EmployeeList physicianFrame = new EmployeeList();
        physicianFrame.setLocationRelativeTo(null);
        physicianFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelPhysicianMouseClicked

    private void jPanelScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelScheduleMouseClicked
        DrugListFrame drugList = new DrugListFrame();
        drugList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelScheduleMouseClicked

    private void jPanelManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelManualMouseClicked
        RoomListFrame roomList = new RoomListFrame();
        roomList.setLocationRelativeTo(null);
        roomList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelManualMouseClicked

    private void jPanelCreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCreateAccountMouseClicked
        CreateAccount ca = new CreateAccount();
        ca.setLocationRelativeTo(null);
        ca.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jPanelCreateAccountMouseClicked

    private void jPanelManual1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelManual1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelManual1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAppName;
    private javax.swing.JLabel jLabelCreateAccount;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelManual;
    private javax.swing.JLabel jLabelManual1;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelPatient;
    private javax.swing.JLabel jLabelPhysician;
    private javax.swing.JLabel jLabelSchedule;
    private javax.swing.JLabel jLabelSlogan;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelCreateAccount;
    private javax.swing.JPanel jPanelManual;
    private javax.swing.JPanel jPanelManual1;
    private javax.swing.JPanel jPanelPatient;
    private javax.swing.JPanel jPanelPhysician;
    private javax.swing.JPanel jPanelSchedule;
    // End of variables declaration//GEN-END:variables
}
