
package gui.admin;

import gui.AddPatientForm;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import logic.AddPerson;
import logic.TableHandler;

public class PatientFrame extends javax.swing.JFrame {

    int selectedRow;
    int id;
    /**
     * Creates new form PatientFrame
     */
    public PatientFrame() {
        initComponents();
        populateTable();
        
        jLabelNoDataFound.setVisible(false);
        jLabelNoDataHint.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelNoDataHint = new javax.swing.JLabel();
        jLabelNoDataFound = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonView = new javax.swing.JButton();
        jComboBoxFilter = new javax.swing.JComboBox<>();
        jLabelSearchPlaceholder = new javax.swing.JLabel();
        jTextFieldSearchBar = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Patients List");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 40, 88, 29);

        jButtonDelete.setText("Delete");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete);
        jButtonDelete.setBounds(780, 30, 72, 23);

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(560, 30, 72, 23);

        jLabelNoDataHint.setText("Make sure that you have selected a filter.");
        jLabelNoDataHint.setEnabled(false);
        jPanel1.add(jLabelNoDataHint);
        jLabelNoDataHint.setBounds(370, 310, 220, 16);

        jLabelNoDataFound.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelNoDataFound.setText("No Data Was Found :(");
        jLabelNoDataFound.setEnabled(false);
        jPanel1.add(jLabelNoDataFound);
        jLabelNoDataFound.setBounds(290, 210, 370, 140);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(870, 450));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(870, 450));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(870, 450));

        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 870, 450);

        jLabel2.setText("Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 10, 25, 16);

        jButtonView.setText("View");
        jButtonView.setEnabled(false);
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonView);
        jButtonView.setBounds(670, 30, 72, 23);

        jComboBoxFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter", "id", "first_name", "last_name", "sex", "email" }));
        jPanel1.add(jComboBoxFilter);
        jComboBoxFilter.setBounds(340, 30, 89, 22);

        jLabelSearchPlaceholder.setText("Look for...");
        jLabelSearchPlaceholder.setEnabled(false);
        jPanel1.add(jLabelSearchPlaceholder);
        jLabelSearchPlaceholder.setBounds(140, 30, 60, 20);

        jTextFieldSearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchBarFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldSearchBar);
        jTextFieldSearchBar.setBounds(130, 30, 210, 22);

        jButtonSearch.setText("Search");
        jButtonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSearchMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSearch);
        jButtonSearch.setBounds(230, 50, 72, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable() {
        TableHandler tableHandler = new TableHandler();
        DefaultTableModel tableModel = tableHandler.getAllData("patients");
        jTable1.setModel(tableModel);
        
        if (jTable1.getRowCount() != 0) {
            int columnCount = jTable1.getColumnCount();
            TableColumn column;
            for (int i = 0; i < columnCount; i++) {
                if (i > 5 && i < 7 || i > 8) {
                    column = jTable1.getColumnModel().getColumn(i);
                    column.setMinWidth(0);
                    column.setMaxWidth(0);
                    column.setWidth(0);
                    column.setPreferredWidth(0);
                } 
            }
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AddPatientForm addPatient = new AddPatientForm(this);
        addPatient.setLocationRelativeTo(null);
        addPatient.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Home home = new Home();
        home.setLocationRelativeTo(null);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        selectedRow = jTable1.getSelectedRow();
        if(selectedRow != -1) {
            jButtonView.setEnabled(true);
            jButtonDelete.setEnabled(true);
            id = (int) jTable1.getValueAt(selectedRow, 0);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        jTable1.requestFocus();
        DetailedPatientFrame.id = id;
        DetailedPatientFrame dpt = new DetailedPatientFrame();
        dpt.setLocationRelativeTo(null);
        dpt.setVisible(true);
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "This will permanently delete patient no. " + id + " record.");
        
        if (result == JOptionPane.YES_OPTION) {
            AddPerson pcrud = new AddPerson();
            if (pcrud.deleteRecord("patients", "id", id)) {
                JOptionPane.showMessageDialog(null, "Patient Record Deleted");
                populateTable();
            } else {
                JOptionPane.showMessageDialog(null, "Something Went Wrong");
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldSearchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchBarFocusGained
        jLabelSearchPlaceholder.setVisible(false);
    }//GEN-LAST:event_jTextFieldSearchBarFocusGained

    private void jTextFieldSearchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchBarFocusLost
        if (jTextFieldSearchBar.getText().isEmpty()) {
            jLabelSearchPlaceholder.setVisible(true);
        }
    }//GEN-LAST:event_jTextFieldSearchBarFocusLost

    private void jButtonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSearchMouseClicked
        if (jTextFieldSearchBar.getText().isEmpty()) {
            populateTable();
            jLabelNoDataFound.setVisible(false);
            jLabelNoDataHint.setVisible(false);
        }else if (jComboBoxFilter.getSelectedIndex() == 0){
            DefaultTableModel tableModel = new DefaultTableModel();
            jTable1.setModel(tableModel);
            jLabelNoDataFound.setVisible(true);
            jLabelNoDataHint.setVisible(true);
        }else {
            TableHandler tableHandler = new TableHandler();
            DefaultTableModel tableModel = tableHandler.getPersonData(jTextFieldSearchBar, jComboBoxFilter, "patients");
            jTable1.setModel(tableModel);

            if (jTable1.getRowCount() != 0) {
                jLabelNoDataFound.setVisible(false);
                jLabelNoDataHint.setVisible(false);

                int columnCount = jTable1.getColumnCount();
                TableColumn column;
                for (int i = 0; i < columnCount; i++) {
                    if (i > 5 && i < 7 || i > 8) {
                        column = jTable1.getColumnModel().getColumn(i);
                        column.setMinWidth(0);
                        column.setMaxWidth(0);
                        column.setWidth(0);
                        column.setPreferredWidth(0);
                    }
                }
            } else {
                jLabelNoDataFound.setVisible(true);
                jLabelNoDataHint.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButtonSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonView;
    private javax.swing.JComboBox<String> jComboBoxFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNoDataFound;
    private javax.swing.JLabel jLabelNoDataHint;
    private javax.swing.JLabel jLabelSearchPlaceholder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldSearchBar;
    // End of variables declaration//GEN-END:variables
}
